alert:
- debug
description: Detects a command that clears or disables any ETW trace log which could indicate a logging evasion.
filter:
- query:
    query_string:
      query: (event_id:"4688" AND (process_command_line.keyword:*\ cl\ *\/Trace* OR process_command_line.keyword:*\ clear\-log\ *\/Trace* OR process_command_line.keyword:*\ sl*\ \/e\:false* OR process_command_line.keyword:*\ set\-log*\ \/e\:false*))
index: logs-endpoint-winevent-security-*
name: a238b5d0-ce2d-4414-a676-7a531b3d13d6_0 Disable of ETW Trace
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


