alert:
- debug
description: Detects FlowCloud malware from threat group TA410.
filter:
- query:
    query_string:
      query: (event_id:("12" OR "13") AND registry_key_path.keyword:(HKLM\\HARDWARE\\\{804423C2\-F490\-4ac3\-BFA5\-13DEDE63A71A\} OR HKLM\\HARDWARE\\\{A5124AF5\-DF23\-49bf\-B0ED\-A18ED3DEA027\} OR HKLM\\HARDWARE\\\{2DB80286\-1784\-48b5\-A751\-B6ED1F490303\} OR HKLM\\SYSTEM\\Setup\\PrintResponsor\\*))
index: logs-endpoint-winevent-sysmon-*
name: 5118765f-6657-4ddb-a487-d7bd673abbf1_0 FlowCloud Malware
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


