alert:
- debug
description: Detects a suspicious Microsoft certutil execution with sub commands like 'decode' sub command, which is sometimes used to decode malicious code with the built-in certutil utility
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:(*\ \-decode\ * OR *\ \/decode\ * OR *\ \-decodehex\ * OR *\ \/decodehex\ * OR *\ \-urlcache\ * OR *\ \/urlcache\ * OR *\ \-verifyctl\ * OR *\ \/verifyctl\ * OR *\ \-encode\ * OR *\ \/encode\ * OR *certutil*\ \-URL* OR *certutil*\ \/URL* OR *certutil*\ \-ping* OR *certutil*\ \/ping*))
index: logs-endpoint-winevent-*
name: e011a729-98a6-4139-b5c4-bf6f6dd8239a_0 Suspicious Certutil Command
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


