alert:
- debug
description: Detects well-known credential dumping tools execution via specific named pipes
filter:
- query:
    query_string:
      query: (event_id:"17" AND pipe_name.keyword:(*\\lsadump* OR *\\cachedump* OR *\\wceservicepipe*))
index: logs-endpoint-winevent-sysmon-*
name: 961d0ba2-3eea-4303-a930-2cf78bbfcc5e_0 Cred Dump-Tools Named Pipes
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


