alert:
- debug
description: Detects the creation of taskmgr.exe process in context of LOCAL_SYSTEM
filter:
- query:
    query_string:
      query: (event_id:"4688" AND user_account:"NT\ AUTHORITY\\SYSTEM" AND process_path.keyword:*\\taskmgr.exe)
index: logs-endpoint-winevent-security-*
name: 9fff585c-c33e-4a86-b3cd-39312079a65f_0 Taskmgr as LOCAL_SYSTEM
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


