alert:
- debug
description: Detects suspect access to svchost process memory such as that used by Invoke-Phantom to kill the winRM windows event logging service.
filter:
- query:
    query_string:
      query: (target_process_path.keyword:*\\windows\\system32\\svchost.exe AND process_granted_access:"0x1f3fff" AND process_call_trace.keyword:(*unknown*))
index: logs-endpoint-winevent-*
name: 166e9c50-8cd9-44af-815d-d1f0c0e90dde_0 Suspect Svchost Memory Asccess
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


