alert:
- debug
description: Detects handle requests and access operations to specific registry keys to calculate the SysKey
filter:
- query:
    query_string:
      query: (event_id:("4656" OR "4663") AND object_type:"key" AND object_name.keyword:(*lsa\\JD OR *lsa\\GBG OR *lsa\\Skew1 OR *lsa\\Data))
index: logs-endpoint-winevent-*
name: 9a4ff3b8-6187-4fd2-8e8b-e0eae1129495_0 SysKey Registry Keys Access
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


