alert:
- debug
description: This rule detects a DHCP server in which a specified Callout DLL (in registry) was loaded
filter:
- query:
    query_string:
      query: (event_id:"1033" AND source_name:"Microsoft\-Windows\-DHCP\-Server")
index: logs-endpoint-winevent-*
name: 13fc89a9-971e-4ca6-b9dc-aa53a445bf40_0 DHCP Server Loaded the CallOut DLL
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


