alert:
- debug
description: Detects persitence via netsh helper
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_path.keyword:*\\netsh.exe AND process_command_line.keyword:*add* AND process_command_line.keyword:*helper*)
index: logs-endpoint-winevent-sysmon-*
name: 56321594-9087-49d9-bf10-524fe8479452_0 Suspicious Netsh DLL Persistence
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


