alert:
- debug
description: Network sniffing refers to using the network interface on a system to monitor or capture information sent over a wired or wireless connection. An adversary may place a network interface into promiscuous mode to passively access data in transit over the network, or use span ports to capture a larger amount of data.
filter:
- query:
    query_string:
      query: (event_id:"4688" AND ((process_path.keyword:*\\tshark.exe AND process_command_line.keyword:*\-i*) OR process_path.keyword:*\\windump.exe))
index: logs-endpoint-winevent-*
name: ba1f7802-adc7-48b4-9ecb-81e227fddfd5_0 Network Sniffing
priority: 4
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


