alert:
- debug
description: Detects the use of rar.exe, on the command line, to create an archive with password protection or with a specific compression level. This is pretty indicative of malicious actions.
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*\ \-hp* AND process_command_line.keyword:*\ \-m*)
index: logs-endpoint-winevent-sysmon-*
name: faa48cae-6b25-4f00-a094-08947fef582f_0 Rar with Password or Compression Level
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


