alert:
- debug
description: Detects process injection using the signed Windows tool Mavinject32.exe
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*\ \/INJECTRUNNING\ *)
index: logs-endpoint-winevent-sysmon-*
name: 17eb8e57-9983-420d-ad8a-2c4976c22eb8_0 MavInject Process Injection
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


