alert:
- debug
description: This rule detects a DHCP server error in which a specified Callout DLL (in registry) could not be loaded
filter:
- query:
    query_string:
      query: (event_id:("1031" OR "1032" OR "1034") AND source_name:"Microsoft\-Windows\-DHCP\-Server")
index: logs-endpoint-winevent-system-*
name: 75edd3fd-7146-48e5-9848-3013d7f0282c_0 DHCP Server Error Failed Loading the CallOut DLL
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


