alert:
- debug
description: Detects known sensitive file extensions accessed on a network share
filter:
- query:
    query_string:
      query: (event_id:("5145") AND share_relative_target_name.keyword:(*.pst OR *.ost OR *.msg OR *.nst OR *.oab OR *.edb OR *.nsf OR *.bak OR *.dmp OR *.kirbi OR *\\groups.xml OR *.rdp))
index: logs-endpoint-winevent-security-*
name: 91c945bc-2ad1-4799-a591-4d00198a1215_0 Suspicious Access to Sensitive File Extensions
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


