alert:
- debug
description: Detects actions caused by the RedMimicry Winnti playbook
filter:
- query:
    query_string:
      query: registry_key_path.keyword:*HKLM\\SOFTWARE\\Microsoft\\HTMLHelp\\data*
index: logs-endpoint-winevent-*
name: 5b175490-b652-4b02-b1de-5b5b4083c5f8_0 RedMimicry Winnti Playbook Registry Manipulation
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


