alert:
- debug
description: Detects usage of findstr to identify and execute a lnk file as seen within the HHS redirect attack
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_path.keyword:*\\findstr.exe AND process_command_line.keyword:*.lnk)
index: logs-endpoint-winevent-security-*
name: 33339be3-148b-4e16-af56-ad16ec6c7e7b_0 Findstr Launching .lnk File
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


