alert:
- debug
description: Detects Octopus Scanner Malware.
filter:
- query:
    query_string:
      query: (event_id:"11" AND file_name.keyword:(*\\AppData\\Local\\Microsoft\\Cache134.dat OR *\\AppData\\Local\\Microsoft\\ExplorerSync.db))
index: logs-endpoint-winevent-*
name: 805c55d9-31e6-4846-9878-c34c75054fe9_0 Octopus Scanner Malware
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


