alert:
- debug
description: Transfering files with well-known filenames (sensitive files with credential data) using network shares
filter:
- query:
    query_string:
      query: (event_id:"5145" AND share_relative_target_name.keyword:(*\\mimidrv* OR *\\lsass* OR *\\windows\\minidump\\* OR *\\hiberfil* OR *\\sqldmpr* OR *\\sam* OR *\\ntds.dit* OR *\\security*))
index: logs-endpoint-winevent-*
name: 910ab938-668b-401b-b08c-b596e80fdca5_0 Transfering Files with Credential Data via Network Shares
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


