alert:
- debug
description: Detect the use of Windows Defender to download payloads
filter:
- query:
    query_string:
      query: (event_id:"4688" AND (process_command_line.keyword:*MpCmdRun.exe* OR file_description:"Microsoft\ Malware\ Protection\ Command\ Line\ Utility") AND (process_command_line.keyword:*DownloadFile* AND process_command_line.keyword:*url*))
index: logs-endpoint-winevent-*
name: 46123129-1024-423e-9fae-43af4a0fa9a5_0 Windows Defender Download Activity
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


