alert:
- debug
description: Detects suspicious PowerShell download command
filter:
- query:
    query_string:
      query: (Message.keyword:*System.Net.WebClient* AND (Message.keyword:*.DownloadFile\(* OR Message.keyword:*.DownloadString\(*))
index: logs-endpoint-winevent-powershell-*
name: 65531a81-a694-4e31-ae04-f8ba5bc33759_0 Suspicious PowerShell Download
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


