alert:
- debug
description: Detects DSParse DLL being loaded by an Office Product
filter:
- query:
    query_string:
      query: (process_path.keyword:(*\\winword.exe OR *\\powerpnt.exe OR *\\excel.exe OR *\\outlook.exe) AND ImageLoaded.keyword:(*\\dsparse.dll*))
index: logs-endpoint-winevent-*
name: a2a3b925-7bb0-433b-b508-db9003263cc4_0 Active Directory Parsing DLL Loaded Via Office Applications
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


