alert:
- debug
description: Detects abusing Windows 10 Narrator's Feedback-Hub
filter:
- query:
    query_string:
      query: ((event_category_type:"DeleteValue" AND registry_key_path.keyword:*\\AppXypsaf9f1qserqevf0sws76dx4k9a5206\\Shell\\open\\command\\DelegateExecute) OR registry_key_path.keyword:*\\AppXypsaf9f1qserqevf0sws76dx4k9a5206\\Shell\\open\\command\\\(Default\))
index: logs-endpoint-winevent-*
name: f663a6d9-9d1b-49b8-b2b1-0637914d199a_0 Narrator's Feedback-Hub Persistence
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


