alert:
- debug
description: This method uses uncommon error codes on failed logons to determine suspicious activity and tampering with accounts that have been disabled or somehow restricted.
filter:
- query:
    query_string:
      query: (event_id:("4625" OR "4776") AND event_status:("0xC0000072" OR "0xC000006F" OR "0xC0000070" OR "0xC0000413" OR "0xC000018C" OR "0xC000015B"))
index: logs-endpoint-winevent-*
name: 9eb99343-d336-4020-a3cd-67f3819e68ee_0 Account Tampering - Suspicious Failed Logon Reasons
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


