alert:
- debug
description: Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
filter:
- query:
    query_string:
      query: (registry_key_path:("HKLM\\System\\CurrentControlSet\\Control\\Lsa\\Security\ Packages" OR "HKLM\\System\\CurrentControlSet\\Control\\Lsa\\OSConfig\\Security\ Packages") AND (NOT (process_path:"C\:\\Windows\\system32\\msiexec.exe" OR process_path:"C\:\\Windows\\syswow64\\MsiExec.exe")))
index: logs-endpoint-winevent-*
name: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc_0 Security Support Provider (SSP) Added to LSA Configuration
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


