alert:
- debug
description: Detects non-system users failing to get a handle of the SCM database.
filter:
- query:
    query_string:
      query: (event_id:"4656" AND object_type:"SC_MANAGER\ OBJECT" AND object_name:"servicesactive" AND Keywords:"Audit\ Failure" AND SubjectLogonId:"0x3e4")
index: logs-endpoint-winevent-*
name: 13addce7-47b2-4ca0-a98f-1de964d1d669_0 SCM Database Handle Failure
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


