alert:
- debug
description: Detects DLL's Loaded Via Word Containing VBA Macros
filter:
- query:
    query_string:
      query: (process_path.keyword:(*\\winword.exe OR *\\powerpnt.exe OR *\\excel.exe OR *\\outlook.exe) AND ImageLoaded.keyword:(*\\VBE7.DLL OR *\\VBEUI.DLL OR *\\VBE7INTL.DLL))
index: logs-endpoint-winevent-*
name: e6ce8457-68b1-485b-9bdd-3c2b5d679aa9_0 VBA DLL Loaded Via Microsoft Word
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


