alert:
- debug
description: This method triggers on rare Kerberos Failure Codes caused by manipulations of Kerberos messages
filter:
- query:
    query_string:
      query: (event_id:("675" OR "4768" OR "4769" OR "4771") AND ticket_failure_code:("0x9" OR "0xA" OR "0xB" OR "0xF" OR "0x10" OR "0x11" OR "0x13" OR "0x14" OR "0x1A" OR "0x1F" OR "0x21" OR "0x22" OR "0x23" OR "0x24" OR "0x26" OR "0x27" OR "0x28" OR "0x29" OR "0x2C" OR "0x2D" OR "0x2E" OR "0x2F" OR "0x31" OR "0x32" OR "0x3E" OR "0x3F" OR "0x40" OR "0x41" OR "0x43" OR "0x44"))
index: logs-endpoint-winevent-security-*
name: f7644214-0eb0-4ace-9455-331ec4c09253_0 Kerberos Manipulation
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


