alert:
- debug
description: Detect various execution methods of the CrackMapExec pentesting framework
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_command_line.keyword:(*cmd.exe\ \/Q\ \/c\ *\ 1>\ \\\\*\\*\\*\ 2>&1 OR *cmd.exe\ \/C\ *\ >\ \\\\*\\*\\*\ 2>&1 OR *cmd.exe\ \/C\ *\ >\ *\\Temp\\*\ 2>&1 OR *powershell.exe\ \-exec\ bypass\ \-noni\ \-nop\ \-w\ 1\ \-C\ \"* OR *powershell.exe\ \-noni\ \-nop\ \-w\ 1\ \-enc\ *))
index: logs-endpoint-winevent-*
name: 058f4380-962d-40a5-afce-50207d36d7e2_0 CrackMapExec Command Execution
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


