alert:
- debug
description: Detects renamed jusched.exe used by cobalt group
filter:
- query:
    query_string:
      query: (event_id:"4688" AND (event_id:"4688" AND (file_description:"Java\ Update\ Scheduler" OR file_description:"Java\(TM\)\ Update\ Scheduler")) AND (NOT (process_path.keyword:(*\\jusched.exe))))
index: logs-endpoint-winevent-*
name: edd8a48c-1b9f-4ba1-83aa-490338cd1ccb_0 Renamed jusched.exe
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


