alert:
- debug
description: Detects service ticket requests using RC4 encryption type
filter:
- query:
    query_string:
      query: ((event_id:"4769" AND ticket_options:"0x40810000" AND ticket_encryption_type:"0x17") AND (NOT (service_name.keyword:$*)))
index: logs-endpoint-winevent-*
name: 496a0e47-0a33-4dca-b009-9e6ca3591f39_0 Suspicious Kerberos RC4 Ticket Encryption
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


