alert:
- debug
description: Detects Netsh commands that allows a suspcious application location on Windows Firewall
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*netsh* AND (process_command_line.keyword:*firewall\ add\ allowedprogram* OR (process_command_line.keyword:*advfirewall\ firewall\ add\ rule* AND process_command_line.keyword:*action\=allow* AND process_command_line.keyword:*program\=*)) AND process_command_line.keyword:(*%TEMP%* OR *\:\\RECYCLER\\* OR *C\:\\$Recycle.bin\\* OR *\:\\SystemVolumeInformation\\* OR *C\:\\Windows\\Tasks\\* OR *C\:\\Windows\\debug\\* OR *C\:\\Windows\\fonts\\* OR *C\:\\Windows\\help\\* OR *C\:\\Windows\\drivers\\* OR *C\:\\Windows\\addins\\* OR *C\:\\Windows\\cursors\\* OR *C\:\\Windows\\system32\\tasks\\* OR *C\:\\Windows\\Temp\\* OR *C\:\\Temp\\* OR *C\:\\Users\\Public\\* OR *%Public%\\* OR *C\:\\Users\\Default\\* OR *C\:\\Users\\Desktop\\* OR *\\Downloads\\* OR *\\Temporary\ Internet\ Files\\Content.Outlook\\* OR *\\Local\ Settings\\Temporary\ Internet\ Files\\*))
index: logs-endpoint-winevent-sysmon-*
name: a35f5a72-f347-4e36-8895-9869b0d5fc6d_0 Netsh Program Allowed with Suspcious Location
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


