alert:
- debug
description: Detect priv users or groups recon based on 4661 eventid and known privileged users or groups SIDs
filter:
- query:
    query_string:
      query: (event_id:"4661" AND object_type:("SAM_USER" OR "SAM_GROUP") AND object_name.keyword:(*\-512 OR *\-502 OR *\-500 OR *\-505 OR *\-519 OR *\-520 OR *\-544 OR *\-551 OR *\-555 OR *admin*))
index: logs-endpoint-winevent-*
name: 35ba1d85-724d-42a3-889f-2e2362bcaf23_0 AD Privileged Users or Groups Reconnaissance
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


