alert:
- debug
description: Detects modification of autostart extensibility point (ASEP) in registry
filter:
- query:
    query_string:
      query: registry_key_path.keyword:(*\\software\\Microsoft\\Windows\\CurrentVersion\\Run* OR *\\software\\Microsoft\\Windows\\CurrentVersion\\RunOnce* OR *\\software\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx* OR *\\software\\Microsoft\\Windows\\CurrentVersion\\RunServices* OR *\\software\\Microsoft\\Windows\\CurrentVersion\\RunServicesOnce* OR *\\software\\Microsoft\\Windows\ NT\\CurrentVersion\\Winlogon\\Userinit* OR *\\software\\Microsoft\\Windows\ NT\\CurrentVersion\\Winlogon\\Shell* OR *\\software\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\AppInit_DLLs* OR *\\software\\Wow6432Node\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\AppInit_DLLs* OR *\\software\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\Load* OR *\\software\\Wow6432Node\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\Load* OR *\\software\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\Run* OR *\\software\\Wow6432Node\\Microsoft\\Windows\ NT\\CurrentVersion\\Windows\\Run* OR *\\software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User\ Shell\ Folders*)
index: logs-endpoint-winevent-*
name: 17f878b8-9968-4578-b814-c4217fc5768c_0 Autorun Keys Modification
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


