alert:
- debug
description: The CrachMapExec pentesting framework implements a PowerShell obfuscation with some static strings detected by this rule.
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_command_line.keyword:*powershell.exe* AND process_command_line.keyword:(*join*split* OR *\(\ $ShellId\[1\]\+$ShellId\[13\]\+'x'\)* OR *\(\ $PSHome\[*\]\+$PSHOME\[*\]\+* OR *\(\ $env\:Public\[13\]\+$env\:Public\[5\]\+'x'\)* OR *\(\ $env\:ComSpec\[4,*,25\]\-Join''\)* OR *\[1,3\]\+'x'\-Join''\)*))
index: logs-endpoint-winevent-*
name: 6f8b3439-a203-45dc-a88b-abf57ea15ccf_0 CrackMapExec PowerShell Obfuscation
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


