alert:
- debug
description: An adversary may compress data (e.g., sensitive documents) that is collected prior to exfiltration in order to make it portable and minimize the amount of data sent over the network
filter:
- query:
    query_string:
      query: (event_id:"4104" AND keywords.keyword:*\-Recurse* AND keywords.keyword:*|* AND keywords.keyword:*Compress\-Archive*)
index: logs-endpoint-winevent-*
name: 6dc5d284-69ea-42cf-9311-fb1c3932a69a_0 Data Compressed - Powershell
priority: 4
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


