alert:
- debug
description: Detects a specific tool and export used by EquationGroup
filter:
- query:
    query_string:
      query: (event_id:"4688" AND ((process_path.keyword:*\\rundll32.exe AND process_command_line.keyword:*,dll_u) OR process_command_line.keyword:*\ \-export\ dll_u\ *))
index: logs-endpoint-winevent-*
name: d465d1d8-27a2-4cca-9621-a800f37cf72e_0 Equation Group DLL_U Load
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


