alert:
- debug
description: When a file is opened, the default program used to open the file (also called the file association or handler) is checked. File association selections are stored in the Windows Registry and can be edited by users, administrators, or programs that have Registry access or by administrators using the built-in assoc utility. Applications can modify the file association for a given file extension to call an arbitrary program when a file with the given extension is opened.
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*cmd* AND process_command_line.keyword:*\/c* AND process_command_line.keyword:*assoc*)
index: logs-endpoint-winevent-*
name: 3d3aa6cd-6272-44d6-8afc-7e88dfef7061_0 Change Default File Association
priority: 4
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


