alert:
- debug
description: Detects invocation of Microsoft Workflow Compiler, which may permit the execution of arbitrary unsigned code.
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_path.keyword:*\\Microsoft.Workflow.Compiler.exe)
index: logs-endpoint-winevent-sysmon-*
name: 419dbf2b-8a9b-4bea-bf99-7544b050ec8d_0 Microsoft Workflow Compiler
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


