alert:
- debug
description: Detects potential mimikatz-like tools accessing LSASS from non system account
filter:
- query:
    query_string:
      query: ((event_id:("4663" OR "4656") AND object_type:"Process" AND object_name.keyword:*\\lsass.exe) AND (NOT (SubjectUserName.keyword:*$)))
index: logs-endpoint-winevent-*
name: 962fe167-e48d-4fd6-9974-11e5b9a5d6d1_0 LSASS Access from Non System Account
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


