alert:
- debug
description: Detects Base64 encoded Shellcode
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*AAAAYInlM* AND process_command_line.keyword:(*OiCAAAAYInlM* OR *OiJAAAAYInlM*))
index: logs-endpoint-winevent-*
name: 2d117e49-e626-4c7c-bd1f-c3c0147774c8_0 PowerShell Base64 Encoded Shellcode
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


