alert:
- debug
description: Detects potential abuse of Active Directory Replication Service (ADRS) from a non machine account to request credentials.
filter:
- query:
    query_string:
      query: ((event_id:"4662" AND object_access_mask:"0x100" AND object_properties.keyword:(*1131f6aa\-9c07\-11d1\-f79f\-00c04fc2dcd2* OR *1131f6ad\-9c07\-11d1\-f79f\-00c04fc2dcd2* OR *89e95b76\-444d\-4c62\-991a\-0facbeda640c*)) AND (NOT (user_name.keyword:*$ OR user_name.keyword:MSOL_*)))
index: logs-endpoint-winevent-*
name: 17d619c1-e020-4347-957e-1d1207455c93_0 Active Directory Replication from Non Machine Account
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


