alert:
- debug
description: Detects all Emotet like process executions that are not covered by the more generic rules
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:(*\ \-e*\ PAA* OR *JABlAG4AdgA6AHUAcwBlAHIAcAByAG8AZgBpAGwAZQ* OR *QAZQBuAHYAOgB1AHMAZQByAHAAcgBvAGYAaQBsAGUA* OR *kAGUAbgB2ADoAdQBzAGUAcgBwAHIAbwBmAGkAbABlA* OR *IgAoACcAKgAnACkAOwAkA* OR *IAKAAnACoAJwApADsAJA* OR *iACgAJwAqACcAKQA7ACQA* OR *JABGAGwAeAByAGgAYwBmAGQ*))
index: logs-endpoint-winevent-sysmon-*
name: d02e8cf5-6099-48cf-9bfc-1eec2d0c7b18_0 Emotet Process Creation
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


