alert:
- debug
description: A login from a public IP can indicate a misconfigured firewall or network boundary.
filter:
- query:
    query_string:
      query: (event_id:"4625" AND (NOT ((src_original_value.keyword:*\-* OR src_original_value.keyword:(10.* OR 192.168.* OR 172.16.* OR 172.17.* OR 172.18.* OR 172.19.* OR 172.20.* OR 172.21.* OR 172.22.* OR 172.23.* OR 172.24.* OR 172.25.* OR 172.26.* OR 172.27.* OR 172.28.* OR 172.29.* OR 172.30.* OR 172.31.* OR 127.* OR 169.254.*) OR src_original_value:"\:\:1" OR src_original_value.keyword:(fe80\:\:* OR fc00\:\:*)))))
index: logs-endpoint-winevent-*
name: f88e112a-21aa-44bd-9b01-6ee2a2bbbed1_0 Failed Logon From Public IP
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


