alert:
- debug
description: Detects disabling Windows Defender threat protection
filter:
- query:
    query_string:
      query: (event_id:("5001" OR "5010" OR "5012" OR "5101") OR (registry_key_path:("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\WinDefend" OR "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\ Defender" OR "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\ Defender") AND Details:"DWORD\ \(0x00000001\)"))
index: logs-endpoint-winevent-*
name: fe34868f-6e0e-4882-81f6-c43aa8f15b62_0 Windows Defender Threat Detection Disabled
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


