alert:
- debug
description: Detects a Powershell process that contains download commands in its command line string
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_path.keyword:*\\powershell.exe AND process_command_line.keyword:(*new\-object\ system.net.webclient\).downloadstring\(* OR *new\-object\ system.net.webclient\).downloadfile\(* OR *new\-object\ net.webclient\).downloadstring\(* OR *new\-object\ net.webclient\).downloadfile\(*))
index: logs-endpoint-winevent-*
name: 3b6ab547-8ec2-4991-b9d2-2b06702a48d7_0 PowerShell Download from URL
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


