alert:
- debug
description: Detects Formbook like process executions that inject code into a set of files in the System32 folder, which executes a special command command line to delete the dropper from the AppData Temp folder. We avoid false positives by excluding all parent process with command line parameters.
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_parent_command_line.keyword:(C\:\\Windows\\System32\\*.exe OR C\:\\Windows\\SysWOW64\\*.exe) AND process_command_line.keyword:(*\ \/c\ del\ \"C\:\\Users\\*\\AppData\\Local\\Temp\\*.exe OR *\ \/c\ del\ \"C\:\\Users\\*\\Desktop\\*.exe OR *\ \/C\ type\ nul\ >\ \"C\:\\Users\\*\\Desktop\\*.exe))
index: logs-endpoint-winevent-*
name: 032f5fb3-d959-41a5-9263-4173c802dc2b_0 Formbook Process Creation
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


