alert:
- debug
description: Detects unusual processes accessing desktop.ini, which can be leveraged to alter how Explorer displays a folder's content (i.e. renaming files) without changing them on disk.
filter:
- query:
    query_string:
      query: (file_name.keyword:*\\desktop.ini AND (NOT (process_path:("C\:\\Windows\\explorer.exe" OR "C\:\\Windows\\System32\\msiexec.exe" OR "C\:\\Windows\\System32\\mmc.exe"))))
index: logs-endpoint-winevent-*
name: 81315b50-6b60-4d8f-9928-3466e1022515_0 Suspicious desktop.ini Action
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


