alert:
- debug
description: Detects suspicious calls of DLLs in rundll32.dll exports by ordinal
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:*\\rundll32.exe\ *,#*)
index: logs-endpoint-winevent-sysmon-*
name: e79a9e79-eb72-4e78-a628-0e7e8f59e89c_0 Suspicious Call by Ordinal
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


