alert:
- debug
description: Detects a Windows command line executable started from MSHTA
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_parent_path.keyword:*\\mshta.exe AND process_path.keyword:(*\\cmd.exe OR *\\powershell.exe OR *\\wscript.exe OR *\\cscript.exe OR *\\sh.exe OR *\\bash.exe OR *\\reg.exe OR *\\regsvr32.exe OR *\\BITSADMIN*))
index: logs-endpoint-winevent-*
name: 03cc0c25-389f-4bf8-b48d-11878079f1ca_0 MSHTA Spawning Windows Shell
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


