alert:
- debug
description: Detects a base64 encoded IEX command string in a process command line
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_command_line.keyword:(*SUVYIChb* OR *lFWCAoW* OR *JRVggKF* OR *aWV4IChb* OR *lleCAoW* OR *pZXggKF* OR *aWV4IChOZX* OR *lleCAoTmV3* OR *pZXggKE5ld* OR *SUVYIChOZX* OR *lFWCAoTmV3* OR *JRVggKE5ld*))
index: logs-endpoint-winevent-*
name: 88f680b8-070e-402c-ae11-d2914f2257f1_0 Encoded IEX
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


