alert:
- debug
description: Well-known TAP software installation. Possible preparation for data exfiltration using tunnelling techniques
filter:
- query:
    query_string:
      query: (event_id:"7045" AND ImagePath.keyword:*tap0901*)
index: logs-endpoint-winevent-system-*
name: 8e4cf0e5-aa5d-4dc3-beff-dc26917744a9_0 Tap Driver Installation
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any

alert:
- debug
description: Well-known TAP software installation. Possible preparation for data exfiltration using tunnelling techniques
filter:
- query:
    query_string:
      query: (event_id:"6" AND ImagePath.keyword:*tap0901*)
index: logs-endpoint-winevent-*
name: 8e4cf0e5-aa5d-4dc3-beff-dc26917744a9-2_0 Tap Driver Installation
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any

alert:
- debug
description: Well-known TAP software installation. Possible preparation for data exfiltration using tunnelling techniques
filter:
- query:
    query_string:
      query: (event_id:"4697" AND ImagePath.keyword:*tap0901*)
index: logs-endpoint-winevent-*
name: 8e4cf0e5-aa5d-4dc3-beff-dc26917744a9-3_0 Tap Driver Installation
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


