alert:
- debug
description: Detects PowerShell called from an executable by the version mismatch method
filter:
- query:
    query_string:
      query: (event_id:"400" AND powershell.engine.version.keyword:(2.* OR 4.* OR 5.*) AND powershell.host.version.keyword:3.*)
index: logs-endpoint-winevent-*
name: c70e019b-1479-4b65-b0cc-cd0c6093a599_0 PowerShell Called from an Executable Version Mismatch
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


