alert:
- debug
description: Detects that a vulnerable Netlogon secure channel connection was allowed, which could be an indicator of CVE-2020-1472.
filter:
- query:
    query_string:
      query: event_id:("5829")
index: logs-endpoint-winevent-system-*
name: a0cb7110-edf0-47a4-9177-541a4083128a_0 Vulnerable Netlogon Secure Channel Connection Allowed
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


