alert:
- debug
description: Detects usage of bitsadmin downloading a file
filter:
- query:
    query_string:
      query: (event_id:"1" AND ((process_path.keyword:(*\\bitsadmin.exe) AND process_command_line.keyword:(*\ \/transfer\ *)) OR process_command_line.keyword:(*copy\ bitsadmin.exe*)))
index: logs-endpoint-winevent-sysmon-*
name: d059842b-6b9d-4ed1-b5c3-5b89143c6ede_0 Bitsadmin Download
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


