alert:
- debug
description: Detects activity that could be related to Baby Shark malware
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_command_line.keyword:(reg\ query\ \"HKEY_CURRENT_USER\\Software\\Microsoft\\Terminal\ Server\ Client\\Default\" OR powershell.exe\ mshta.exe\ http* OR cmd.exe\ \/c\ taskkill\ \/im\ cmd.exe))
index: logs-endpoint-winevent-*
name: 2b30fa36-3a18-402f-a22d-bf4ce2189f35_0 Baby Shark Activity
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


