alert:
- debug
description: Detect modification of services configuration (ImagePath, FailureCommand and ServiceDLL) in registry by processes with Medium integrity level
filter:
- query:
    query_string:
      query: (IntegrityLevel:"Medium" AND registry_key_path.keyword:*\\services\\* AND registry_key_path.keyword:(*\\ImagePath OR *\\FailureCommand OR *\\Parameters\\ServiceDll))
index: logs-endpoint-winevent-*
name: 0f9c21f1-6a73-4b0e-9809-cb562cb8d981_0 Possible Privilege Escalation via Service Permissions Weakness
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


