alert:
- debug
description: Detects a new and suspicious printer port creation in Registry that could be an attempt to exploit CVE-2020-1048
filter:
- query:
    query_string:
      query: (registry_key_path.keyword:HKLM\\SOFTWARE\\Microsoft\\Windows\ NT\\CurrentVersion\\Ports* AND event_category_type:("SetValue" OR "DeleteValue" OR "CreateValue") AND Details.keyword:(*.dll* OR *.exe* OR *.bat* OR *.com* OR *C\:*))
index: logs-endpoint-winevent-*
name: 7ec912f2-5175-4868-b811-ec13ad0f8567_0 Suspicious New Printer Ports in Registry (CVE-2020-1048)
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


