alert:
- debug
description: Detects specific process characteristics of Chinese TAIDOOR RAT malware load
filter:
- query:
    query_string:
      query: (event_id:"4688" AND (process_command_line.keyword:(*dll,MyStart* OR *dll\ MyStart*) OR (event_id:"4688" AND process_command_line.keyword:(*\ MyStart) AND process_command_line.keyword:(*rundll32.exe*))))
index: logs-endpoint-winevent-security-*
name: d1aa3382-abab-446f-96ea-4de52908210b_0 TAIDOOR RAT DLL Load
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


