alert:
- debug
description: Detect AD credential dumping using impacket secretdump HKTL
filter:
- query:
    query_string:
      query: (event_id:"5145" AND share_name.keyword:\\*\\ADMIN$ AND share_relative_target_name.keyword:SYSTEM32\\*.tmp)
index: logs-endpoint-winevent-security-*
name: 252902e3-5830-4cf6-bf21-c22083dfd5cf_0 Possible Impacket SecretDump Remote Activity
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


