alert:
- debug
description: Detects the use of Windows Credential Editor (WCE)
filter:
- query:
    query_string:
      query: (event_id:"1" AND (hash_imphash:("a53a02b997935fd8eedcb5f7abab9b9f" OR "A53A02B997935FD8EEDCB5F7ABAB9B9F" OR "e96a73c7bf33a464c510ede582318bf2" OR "E96A73C7BF33A464C510EDE582318BF2") OR (process_command_line.keyword:*.exe\ \-S AND process_parent_path.keyword:*\\services.exe)))
index: logs-endpoint-winevent-*
name: 7aa7009a-28b9-4344-8c1f-159489a390df_0 Windows Credential Editor
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


