alert:
- debug
description: detects execution of psexec or paexec with renamed service name, this rule helps to filter out the noise if psexec is used for legit purposes or if attacker uses a different psexec client other than sysinternal one
filter:
- query:
    query_string:
      query: ((event_id:"5145" AND share_name.keyword:\\*\\IPC$ AND share_relative_target_name.keyword:(*\-stdin OR *\-stdout OR *\-stderr)) AND (NOT (event_id:"5145" AND share_name.keyword:\\*\\IPC$ AND share_relative_target_name.keyword:PSEXESVC*)))
index: logs-endpoint-winevent-security-*
name: c462f537-a1e3-41a6-b5fc-b2c2cef9bf82_0 Suspicious PsExec Execution
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


