alert:
- debug
description: Detects EmpireMonkey APT reported Activity
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:(*\/i\:%APPDATA%\\logs.txt\ scrobj.dll) AND (process_path.keyword:(*\\cutil.exe) OR file_description:("Microsoft\(C\)\ Registerserver")))
index: logs-endpoint-winevent-sysmon-*
name: 10152a7b-b566-438f-a33c-390b607d1c8d_0 Empire Monkey
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


