alert:
- debug
description: Detects Access to LSASS Process
filter:
- query:
    query_string:
      query: (event_id:"1121" AND process_path.keyword:*\\lsass.exe)
index: logs-*
name: a0a278fe-2c0e-4de2-ac3c-c68b08a9ba98_0 LSASS Access Detected via Attack Surface Reduction
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


