alert:
- debug
description: Detect an interactive AT job, which may be used as a form of privilege escalation
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_path.keyword:*\\at.exe AND process_command_line.keyword:*interactive*)
index: logs-endpoint-winevent-sysmon-*
name: 60fc936d-2eb0-4543-8a13-911c750a1dfc_0 Interactive AT Job
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


