alert:
- debug
description: Detects the usage of tsclient share to place a backdoor on the RDP source machine's startup folder
filter:
- query:
    query_string:
      query: (process_path.keyword:*\\mstsc.exe AND file_name.keyword:*\\Microsoft\\Windows\\Start\ Menu\\Programs\\Startup\\*)
index: logs-endpoint-winevent-*
name: 52753ea4-b3a0-4365-910d-36cff487b789_0 Hijack Legit RDP Session to Move Laterally
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


