alert:
- debug
description: Well-known TAP software installation. Possible preparation for data exfiltration using tunneling techniques
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_path.keyword:*\\tapinstall.exe)
index: logs-endpoint-winevent-*
name: 99793437-3e16-439b-be0f-078782cf953d_0 Tap Installer Execution
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


