alert:
- debug
description: Detects the creation of a named pipe used by known APT malware
filter:
- query:
    query_string:
      query: (event_id:("17" OR "18") AND pipe_name.keyword:(\\isapi_http OR \\isapi_dg OR \\isapi_dg2 OR \\sdlrpc OR \\ahexec OR \\winsession OR \\lsassw OR \\46a676ab7f179e511e30dd2dc41bd388 OR \\9f81f59bc58452127884ce513865ed20 OR \\e710f28d59aa529d6792ca6ff0ca1b34 OR \\rpchlp_3 OR \\NamePipe_MoreWindows OR \\pcheap_reuse OR \\msagent_* OR \\gruntsvc))
index: logs-endpoint-winevent-sysmon-*
name: fe3ac066-98bb-432a-b1e7-a5229cb39d4a_0 Malicious Named Pipe
priority: 1
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


