alert:
- debug
description: Detects a suspicious command line execution that invokes PowerShell with reference to an AppData folder
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line.keyword:(*\ \/c\ powershell*\\AppData\\Local\\* OR *\ \/c\ powershell*\\AppData\\Roaming\\*))
index: logs-endpoint-winevent-sysmon-*
name: ac175779-025a-4f12-98b0-acdaeb77ea85_0 PowerShell Script Run in AppData
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


