alert:
- debug
description: Detects a suspicious exection from an uncommon folder
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_path.keyword:(*\\$Recycle.bin OR *\\Users\\All\ Users\\* OR *\\Users\\Default\\* OR *\\Users\\Public\\* OR C\:\\Perflogs\\* OR *\\config\\systemprofile\\* OR *\\Windows\\Fonts\\* OR *\\Windows\\IME\\* OR *\\Windows\\addins\\*))
index: logs-endpoint-winevent-security-*
name: 3dfd06d2-eaf4-4532-9555-68aca59f57c4_0 Execution in Non-Executable Folder
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


