alert:
- debug
description: Detects process handle on LSASS process with certain access mask
filter:
- query:
    query_string:
      query: ((event_id:"4656" AND object_name.keyword:*\\lsass.exe AND object_access_mask.keyword:(*0x40* OR *0x1400* OR *0x1000* OR *0x100000* OR *0x1410* OR *0x1010* OR *0x1438* OR *0x143a* OR *0x1418* OR *0x1f0fff* OR *0x1f1fff* OR *0x1f2fff* OR *0x1f3fff*)) OR ((event_id:"4663" AND object_name.keyword:*\\lsass.exe AND object_access_list.keyword:(*4484* OR *4416*)) AND (NOT (process_path.keyword:(*\\wmiprvse.exe OR *\\taskmgr.exe OR *\\procexp64.exe OR *\\procexp.exe OR *\\lsm.exe OR *\\csrss.exe OR *\\wininit.exe OR *\\vmtoolsd.exe OR *\\minionhost.exe OR *\\VsTskMgr.exe)))))
index: logs-endpoint-winevent-security-*
name: 4a1b6da0-d94f-4fc3-98fc-2d9cb9e5ee76_0 Generic Password Dumper Activity on LSASS
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


