alert:
- debug
description: Detects potential COM object hijacking leveraging the COM Search Order
filter:
- query:
    query_string:
      query: (registry_key_path.keyword:HKU\\*_Classes\\CLSID\\*\\InProcServer32\\\(Default\) AND (NOT (Details.keyword:(%%systemroot%%\\system32\\* OR %%systemroot%%\\SysWow64\\* OR *\\AppData\\Local\\Microsoft\\OneDrive\\*\\FileCoAuthLib64.dll OR *\\AppData\\Local\\Microsoft\\OneDrive\\*\\FileSyncShell64.dll OR *\\AppData\\Local\\Microsoft\\TeamsMeetingAddin\\*\\Microsoft.Teams.AddinLoader.dll))))
index: logs-endpoint-winevent-*
name: a0ff33d8-79e4-4cef-b4f3-9dc4133ccd12_0 Windows Registry Persistence COM Search Order Hijacking
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


