alert:
- debug
description: Downloads payload from remote server
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_path.keyword:(*\\powerpnt.exe OR *\\winword.exe OR *\\excel.exe) AND process_command_line.keyword:*http*)
index: logs-endpoint-winevent-*
name: 0c79148b-118e-472b-bdb7-9b57b444cc19_0 Malicious Payload Download via Office Binaries
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


