alert:
- debug
buffer_time:
  minutes: 5
description: Detects multiple suspicious process in a limited timeframe
doc_type: doc
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line:("arp.exe" OR "at.exe" OR "attrib.exe" OR "cscript.exe" OR "dsquery.exe" OR "hostname.exe" OR "ipconfig.exe" OR "mimikatz.exe" OR "nbtstat.exe" OR "net.exe" OR "netsh.exe" OR "nslookup.exe" OR "ping.exe" OR "quser.exe" OR "qwinsta.exe" OR "reg.exe" OR "runas.exe" OR "sc.exe" OR "schtasks.exe" OR "ssh.exe" OR "systeminfo.exe" OR "taskkill.exe" OR "telnet.exe" OR "tracert.exe" OR "wscript.exe" OR "xcopy.exe" OR "pscp.exe" OR "copy.exe" OR "robocopy.exe" OR "certutil.exe" OR "vssadmin.exe" OR "powershell.exe" OR "wevtutil.exe" OR "psexec.exe" OR "bcedit.exe" OR "wbadmin.exe" OR "icacls.exe" OR "diskpart.exe"))
index: logs-endpoint-winevent-*
max_threshold: 5
metric_agg_key: _id
metric_agg_type: cardinality
name: 61ab5496-748e-4818-a92f-de78e20fe7f1_0 Quick Execution of a Series of Suspicious Commands
priority: 4
query_key: host_name.keyword
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: metric_aggregation


