alert:
- debug
description: Detects the attack technique pass the hash which is used to move laterally inside the network
filter:
- query:
    query_string:
      query: ((logon_type:"3" AND logon_process_name:"NtLmSsp" AND src_host_name:"%Workstations%" AND host_name:"%Workstations%" AND (event_id:"4624" OR event_id:"4625")) AND (NOT (user_name:"ANONYMOUS\ LOGON")))
index: logs-endpoint-winevent-*
name: f8d98d6c-7a07-4d74-b064-dd4a3c244528_0 Pass the Hash Activity
priority: 3
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any


